extend = [
    { path = "rust/Makefile.toml" },
    { path = "python/Makefile.toml" },
    { path = "java/Makefile.toml" },
    { path = "c/Makefile.toml" },
]

[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.default]
