[tasks.c]
command = "make"
args = ["cargo-build_longbridge-c"]
cwd = "cmake.build"

[tasks.c-release]
command = "make"
args = ["cargo-build_longbridge-c"]
cwd = "cmake.build"

[tasks.c.windows]
command = "msbuild"
args = [
    "longbridge.sln",
    "-p:Configuration=Debug",
    "/t:cargo-build_longbridge-c",
]
cwd = "cmake.build"

[tasks.c-release.windows]
command = "msbuild"
args = [
    "longbridge.sln",
    "-p:Configuration=Release",
    "/t:cargo-build_longbridge-c",
]
cwd = "cmake.build"

[tasks.c-test]
command = "make"
args = ["test-c"]
cwd = "cmake.build"

[tasks.c-test.windows]
command = "msbuild"
args = ["longbridge.sln", "-p:Configuration=Debug", "/t:test-c"]
cwd = "cmake.build"
