[tasks.java]
command = "cargo"
args = ["build", "-p", "longbridge-java"]

[tasks.javah]
command = "javac"
args = [
    "-h",
    "c",
    "-sourcepath",
    "javasrc",
    "-d",
    "classes",
    "javasrc/com/longbridge/SdkNative.java",
]
cwd = "java"

[tasks.move-jni-target]
script_runner = "@rust"
script = '''
fn main() {
    let _ = std::fs::remove_dir_all("java/javasrc/target/natives");

    #[cfg(all(target_os = "linux", target_arch = "x86_64"))]
    {
        std::fs::create_dir_all("java/javasrc/target/natives/linux_64").unwrap();
        std::fs::copy(
            "target/debug/longbridge_java.so",
            "java/javasrc/target/natives/linux_64/longbridge_java.so"
        ).unwrap();
    }

    #[cfg(all(target_os = "macos", target_arch = "x86_64"))]
    {
        std::fs::create_dir_all("java/javasrc/target/natives/osx_64").unwrap();
        std::fs::copy(
            "target/debug/longbridge_java.so",
            "java/javasrc/target/natives/osx_64/longbridge_java.so"
        ).unwrap();
    }

    #[cfg(all(target_os = "macos", target_arch = "aarch64"))]
    {
        std::fs::create_dir_all("java/javasrc/target/natives/osx_arm64").unwrap();
        std::fs::copy(
            "target/debug/longbridge_java.dylib",
            "java/javasrc/target/natives/osx_arm64/longbridge_java.dylib"
        ).unwrap();
    }

    #[cfg(all(target_os = "windows", target_arch = "x86_64"))]
    {
        std::fs::create_dir_all("java/javasrc/target/natives/windows_64").unwrap();
        std::fs::copy(
            "target/debug/longbridge_java.dll",
            "java/javasrc/target/natives/windows_64/longbridge_java.dll"
        ).unwrap();
    }
}
'''

[tasks.package-debug-jar]
dependencies = ["java", "move-jni-target", "mvn-package"]

[tasks.compile-java-test]
command = "javac"
cwd = "java"
args = [
    "-cp",
    "libs/native-lib-loader-2.4.0.jar;libs/slf4j-api-1.7.30.jar;",
    "-sourcepath",
    "javasrc/src/main/java",
    "-d",
    "classes",
    "test/Main.java",
]

[tasks.test-java]
command = "java"
args = [
    "-Djava.library.path=target/debug",
    "-cp",
    "java/classes;java/libs/native-lib-loader-2.4.0.jar;java/libs/slf4j-api-1.7.30.jar;",
    "Main",
]
dependencies = ["java", "compile-java-test"]
