[tasks.build-python-sdk]
command = "maturin"
args = ["build"]
cwd = "python"
dependencies = ["install-maturin"]

[tasks.install-maturin]
command = "pip"
args = ["install", "maturin>=0.12,<0.13"]

[tasks.install-python-sdk.windows]
command = "pip"
args = [
    "install",
    "target/wheels/longbridge_sdk-0.1.0-cp310-none-win_amd64.whl",
    "-I",
]
dependencies = ["build-python-sdk"]

[tasks.install-python-sdk.linux]
command = "pip"
args = ["install", "longbridge_sdk-0.1.0-cp38-cp38-linux_x86_64.whl", "-I"]
dependencies = ["build-python-sdk"]
