[package]
edition = "2021"
name = "longbridge-nodejs"
version = "0.2.8"

[lib]
crate-type = ["cdylib"]

[dependencies]
longbridge = { path = "../rust", version = "0.2.8" }
longbridge-nodejs-macros = { path = "crates/macros", version = "0.2.8" }

# napi = { version = "2.4.3", default-features = false, features = ["napi4"] }
# napi-derive = "2.4.1"
napi = { git = "https://github.com/sunli829/napi-rs", default-features = false, features = [
    "napi4",
    "chrono_date",
    "async",
] }
napi-derive = { git = "https://github.com/sunli829/napi-rs" }
rust_decimal = { version = "1.23.1", features = ["maths"] }
chrono = "0.4.19"
time = "0.3.9"
tokio = { version = "1.18.2", features = ["rt", "time"] }
parking_lot = "0.12.0"

[build-dependencies]
napi-build = "2.0.0"

[profile.release]
lto = true
