name: Docs
on:
  push:
    branches:
      - release

jobs:
  build-api-docs:
    name: Build API docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rust-docs
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Build Rust docs
        run: cargo doc -p longbridge --no-deps
      - name: Build Python wheels
        uses: messense/maturin-action@v1
        with:
          target: "x86_64"
          manylinux: auto
          args: -i 3.9 --release --out dist --no-sdist -m python/Cargo.toml
      - name: Install built wheel
        run: |
          pip install longbridge --no-index --find-links dist --force-reinstall
          python -c "import longbridge"

      - name: Build Python docs
        run: |
          pip install -r docs/requirements.txt
          mkdocs build
        working-directory: ./python

      - name: Build Node.js docs
        run: |
          npm install -g typedoc
          typedoc
        working-directory: ./nodejs

      - name: Build Java docs
        working-directory: ./java/javasrc
        run: mvn javadoc:javadoc

      - name: Get SDK Version
        run: |
          echo RUST_SDK_VERSION=$(sed -nE 's/^\s*version = "(.*?)"/\1/p' rust/Cargo.toml) >> $GITHUB_ENV
          echo PYTHON_SDK_VERSION=$(sed -nE 's/^\s*version = "(.*?)"/\1/p' python/Cargo.toml) >> $GITHUB_ENV
          echo NODEJS_SDK_VERSION=$(sed -nE 's/^\s*version = "(.*?)"/\1/p' nodejs/Cargo.toml) >> $GITHUB_ENV
          echo JAVA_SDK_VERSION=$(sed -nE 's/^\s*version = "(.*?)"/\1/p' java/Cargo.toml) >> $GITHUB_ENV

      - name: Copy to gh-pages
        run: |
          mkdir -p gh-pages
          mkdir -p gh-pages/rust
          mkdir -p gh-pages/python
          mkdir -p gh-pages/nodejs
          mkdir -p gh-pages/java
          mv -f target/doc gh-pages/rust/$RUST_SDK_VERSION
          mv -f python/site gh-pages/python/$PYTHON_SDK_VERSION
          mv -f nodejs/docs gh-pages/nodejs/$NODEJS_SDK_VERSION
          mv -f java/javasrc/target/site/apidocs gh-pages/java/$JAVA_SDK_VERSION
          python .github/misc/render_docs_index.py > gh-pages/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.1
        with:
          emptyCommits: true
          keepFiles: false
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: gh-pages
